### PR TITLE
Fix open graph and twitter metadata

### LINKED ISSUE #137: [BUG] Open Graph data does not work properly
Components are not rendering until the page is mounted leading to issues with Open Graph and twitter metadata.

### PR DESCRIPTION
**Pull request by neokry**
## Description

OG and twitter metadata is not loading correctly due to several checks before the inital render. To prevent this I've remove the `useIsMounted` check from `app.tsx` and reworked pages that use `DaoLayout.tsx` to check for DAO addresses in `getServerSideProps`.

## Motivation & context

fixes #137 

## Code review

Does removing the mounted / address checks break any pages? Is OG data loading properly for the homepage, DAO token pages and proposal pages on supported platforms (twitter, imessage etc)?

In `dao/[token]/[tokenId]` I've changed the component to use the dao addresses passed in from `getServerSideProps` instead of `useDAOStore` is this alright to do or should I make it work with the DAO store?

Are cache times for `proposal/create` and `proposal/review` pages reasonable?

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I have done a self-review of my own code
- [x] Any new and existing tests pass locally with my changes
- [x] My changes generate no new warnings (lint warnings, console warnings, etc)

### CODE REVIEW

**Comment by neokry** [comment]
Realized the proposal and dao pages also have issues with OG data. Converted this to a draft while I figure out the best way to handle those cases

**Comment by neokry** [comment]
```
  const { data } = useContractRead({
    enabled: !!token,
    abi: managerAbi,
    address: PUBLIC_MANAGER_ADDRESS,
    functionName: 'getAddresses',
    args: [token as AddressType],
  })

  useEffect(() => {
    if (data) {
      setAddresses({
        token: token as AddressType,
        auction: data?.auction,
        governor: data?.governor,
        metadata: data?.metadata,
        treasury: data?.treasury,
      })
    }
  }, [setAddresses, data, token])

  if (!data) return null

  const hasMissingAddresses = Object.values(data).includes(ethers.constants.AddressZero)
  if (hasMissingAddresses) {
    return <Flex className={notFoundWrap}>404 - Page Not Found</Flex>
  }
```

This seems to be the main blocker on those pages. What do you think is the best change for this @nadiakiamilev ? We could run this check in getServerSideProps for the pages that use DAO layout.

**Comment by nadiakiamilev** [comment]
> ```
>   const { data } = useContractRead({
>     enabled: !!token,
>     abi: managerAbi,
>     address: PUBLIC_MANAGER_ADDRESS,
>     functionName: 'getAddresses',
>     args: [token as AddressType],
>   })
> 
>   useEffect(() => {
>     if (data) {
>       setAddresses({
>         token: token as AddressType,
>         auction: data?.auction,
>         governor: data?.governor,
>         metadata: data?.metadata,
>         treasury: data?.treasury,
>       })
>     }
>   }, [setAddresses, data, token])
> 
>   if (!data) return null
> 
>   const hasMissingAddresses = Object.values(data).includes(ethers.constants.AddressZero)
>   if (hasMissingAddresses) {
>     return <Flex className={notFoundWrap}>404 - Page Not Found</Flex>
>   }
> ```
> 
> This seems to be the main blocker on the pages using `DaoLayout.tsx`. What do you think is the best change for this @nadiakiamilev ? We could run this check in getServerSideProps for the pages that use DAO layout.

Hey that makes sense! We did it client side initially because it was a simpler route, but it does make sense to do it server side and i think that would enable better handling of non-valid daos. I think that exploration makes sense

**Comment by neokry** [comment]
Just made that change and updated the original description / code review section. Opening this PR for review now.

File: apps/web/src/layouts/DaoLayout.tsx [hunk 1]
```diff
@@ -20,13 +17,10 @@ function DaoLayout({ children }: { children: ReactNode }) {
...
-  const { data } = useContractRead({
-    enabled: !!token,
-    abi: managerAbi,
-    address: PUBLIC_MANAGER_ADDRESS,
-    functionName: 'getAddresses',
-    args: [token as AddressType],
-  })
+  const { data } = useSWR(
+    token ? [SWR_KEYS.DAO_ADDRESSES, token] : null,
+    async () => await getAddresses(token as AddressType)
```
Comment (nadiakiamilev) [inline apps/web/src/layouts/DaoLayout.tsx:22]: do we feel like we need to re-fetch this data client side? I feel like it can just be passed down on the initial page load

**Review by nadiakiamilev — APPROVED** [review]
this looks good! i wonder if we need to refetch this data client side though or even use swr for it as it feels like we just want to pass this down as props on the initial call and it's likely not to change? what are your thoughts there?

File: apps/web/src/layouts/DaoLayout.tsx (hunk 1 above)
Comment (neokry) [reply apps/web/src/layouts/DaoLayout.tsx:22]: was thinking it could be relevant for upgrade scenarios but just realized that the addresses will stay static through an upgrade so I can rework to read the props in the layout and remove SWR.

Comment (nadiakiamilev) [reply apps/web/src/layouts/DaoLayout.tsx:22]: sounds good!

**Comment by neokry** [comment]
forgot to mention made those changes to remove swr yesterday. would love a second set of eyes on the latest commit @nadiakiamilev @taayyohh
